include:
  - path: ragflow/docker/docker-compose-gpu.yml

name: facet-ii-chatbot

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: langfuse_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: langfuse_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  langfuse:
    image: langfuse/langfuse:2
    depends_on:
      - postgres
    environment:
      DATABASE_HOST: postgres
      DATABASE_USERNAME: langfuse_user
      DATABASE_PASSWORD: password
      DATABASE_NAME: langfuse_db
      DATABASE_PORT: 5432
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: "secret"
      SALT: "salt"
    ports:
      - "3000:3000"
    restart: unless-stopped

  pipelines:
    build:
      context: ./pipelines
      dockerfile: Dockerfile
    image: pipelines:latest
    depends_on:
      - langfuse
    ports:
      - "9099:9099"
    volumes:
      - pipelines_data:/app/pipelines
    restart: always
    env_file:
      - .env

  open-webui:
    build:
        context: ./open-webui
        dockerfile: Dockerfile
        args:
          USE_CUDA: "false"
    depends_on:
      - pipelines
      - ollama
    environment:
      OLLAMA_BASE_URL: http://ollama:11434
    ports:
      - "3001:8080"
    volumes:
      - open-webui:/app/backend/data
    restart: always

  ollama:
    image: ollama/ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    restart: always

volumes:
  postgres_data:
  pipelines_data:
  ollama:
  open-webui:
